[AZURE_OPENAI]
AZURE_OPENAI_API_KEY = "de64d117a39044389a563c8b2e244e1b"
AZURE_OPENAI_ENDPOINT = "https://arpitayushideepanjan.openai.azure.com/"
AZURE_OPENAI_EMBEDDING_MODEL_NAME = "ayushi-text-embedding-ada-002"
AZURE_OPENAI_DEPLOYMENT = "ayushi-gpt-35-turbo"
OPENAI_API_VERSION = "2024-02-01"

[PINECONE]
PINECONE_API_KEY = "197709cd-bcef-4eae-b15d-f9011cbf5d93"

[LANGSMITH]
LANGSMITH_API_KEY = "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"
LANGCHAIN_PROJECT = "first-deployment"